//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCSINH
    {
        public int id { get; set; }
        public string tenhs { get; set; }
        public string diachi { get; set; }
        public Nullable<int> malop { get; set; }
    
        public virtual LOP LOP { get; set; }
    }
}
