//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOANCHI
    {
        public int ID { get; set; }
        public Nullable<decimal> sotien { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public string chitiet { get; set; }
        public int loaikhoanchi { get; set; }
        public string nguoithem { get; set; }
    
        public virtual LOAIKHOANCHI LOAIKHOANCHI1 { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
